export const INIT_GAMES_LIST_SUCCESS = 'INIT_GAMES_LIST_SUCCESS';
export const INIT_GAMES_LIST_FAILED = 'INIT_GAMES_LIST_FAILED';

export const FETCH_MORE_GAMES_SUCCESS = 'FETCH_MORE_GAMES_SUCCESS';

export const HANDLE_SHOW_MODAL = 'HANDLE_SHOW_MODAL';
export const HANDLE_HIDE_MODAL = 'HANDLE_HIDE_MODAL';

export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const SET_SEARCH_VALUE_TO_STATE = 'SET_SEARCH_VALUE_TO_STATE';
export const GET_DATA_AFTER_SEARCHING = 'GET_DATA_AFTER_SEARCHING';

export const GET_DATA_FROM_LOCAL_STORAGE = 'GET_DATA_FROM_LOCAL_STORAGE';
